"""Owned WSP table fixture with literal, independent event and table truth."""

from pathlib import Path
from xml.etree import ElementTree as ET

import numpy as np

G = "http://www.isac-net.org/std/Gating-ML/v2.0/gating"
T = "http://www.isac-net.org/std/Gating-ML/v2.0/transformations"
D = "http://www.isac-net.org/std/Gating-ML/v2.0/datatypes"

VALUES = (
    np.array([[10, 6], [20, 12], [30, 30]], dtype=float),
    np.array([[40, 25], [50, 27], [60, 30], [70, 38]], dtype=float),
)
NAMES = ("Zulu control.fcs", "Alpha treated.fcs")
# These literals are not generated by the parser or table engine.
TRUTH = {
    "Acquired": [3, 4],
    "Cells n": [2, 2],
    "Responsive %": [50, 50],
    "Comp signal": [1.5, 3.5],
    "Raw signal": [9, 26],
    "Control signal": [1.5, 1.5],
    "Relative signal": [100, 100 * 3.5 / 1.5],
    "First acquisition": [3, 3],
    "Previous delta": [None, 1],
    "Next delta": [-1, None],
    "Dose value": ["2", "3"],
    "Metadata events": ["3", "4"],
    "Batch value": ["Workspace cohort", "Workspace cohort"],
    "Double hidden": [6, 8],
}


def workspace_tree():
    root = ET.Element("Workspace", flowJoVersion="10.8.1")
    samples = ET.SubElement(root, "SampleList")
    for index, name in enumerate(NAMES, 1):
        sample = ET.SubElement(samples, "Sample")
        ET.SubElement(sample, "DataSet", sampleID=str(index), uri=f"file:/unopened/{name}")
        keywords = ET.SubElement(sample, "Keywords")
        for key, value in (
            ("$TOT", str(len(VALUES[index - 1]))),
            ("Dose", "999"),
            ("Batch", "Workspace cohort"),
        ):
            ET.SubElement(keywords, "Keyword", name=key, value=value)
        matrix = ET.SubElement(
            sample,
            f"{{{T}}}spilloverMatrix",
            {
                f"{{{T}}}id": f"matrix-{index}",
                "name": "Independent X/Y spillover",
                "prefix": "Comp-",
            },
        )
        parameters = ET.SubElement(matrix, f"{{{D}}}parameters")
        for parameter in ("X", "Y"):
            ET.SubElement(parameters, f"{{{D}}}parameter", {f"{{{D}}}name": parameter})
        for row in ((1, 0.5), (0, 1)):
            spillover = ET.SubElement(matrix, f"{{{T}}}spillover")
            for parameter, value in zip(("X", "Y"), row, strict=True):
                ET.SubElement(
                    spillover,
                    f"{{{T}}}coefficient",
                    {
                        f"{{{D}}}parameter": parameter,
                        f"{{{T}}}value": str(value),
                    },
                )
        node = ET.SubElement(sample, "SampleNode", sampleID=str(index), name=name)
        subpopulations = ET.SubElement(node, "Subpopulations")

        def population(parent, name, parameter, low, high):
            population = ET.SubElement(parent, "Population", name=name)
            gate = ET.SubElement(population, "Gate")
            rectangle = ET.SubElement(gate, f"{{{G}}}RectangleGate")
            dimension = ET.SubElement(
                rectangle,
                f"{{{G}}}dimension",
                {
                    f"{{{G}}}min": str(low),
                    f"{{{G}}}max": str(high),
                },
            )
            ET.SubElement(dimension, f"{{{D}}}fcs-dimension", {f"{{{D}}}name": parameter})
            return population

        cells = population(subpopulations, "Cells", "X", 0, 25 if index == 1 else 60)
        population(
            ET.SubElement(cells, "Subpopulations"),
            "Responsive",
            "Comp-Y",
            1,
            2 if index == 1 else 4,
        )
    groups = ET.SubElement(root, "Groups")
    group_node = ET.SubElement(groups, "GroupNode", name="Control only")
    group = ET.SubElement(group_node, "Group", name="Control only")
    refs = ET.SubElement(group, "SampleRefs")
    ET.SubElement(refs, "SampleRef", sampleID="1")
    editor = ET.SubElement(root, "TableEditor")
    table = ET.SubElement(editor, "Table", name="WSP Main")
    ET.SubElement(table, "Iteration", iterationType="SAMPLE", groupName="workspaceSelection")

    def column(name, **attributes):
        attributes = {"rename": name, "valueType": "statistic", "name": name, **attributes}
        return ET.SubElement(table, "TColumn", attributes)

    column("Acquired", statistic="Count", analysisPath="Ungated", heatMap="1")
    column("Cells n", statistic="Count", analysisPath="Cells")
    column("Responsive %", statistic="fj.stat.freqofparent", analysisPath="Cells/Responsive")
    column("Comp signal", statistic="Mean", analysisPath="Cells", parameterName="Comp-Y")
    column("Raw signal", statistic="Mean", analysisPath="Cells", parameterName="Y")
    column(
        "Control signal",
        statistic="Mean",
        analysisPath="Cells",
        parameterName="Comp-Y",
        iscontrolvalue="1",
    )
    column("Dose value", valueType="keyword", keyword="Dose")
    column("Metadata events", valueType="keyword", keyword="$TOT")
    column("Batch value", valueType="keyword", keyword="Batch")
    column(
        "Relative signal",
        valueType="formula",
        formula='<Cell column="Comp signal"/> / <Cell column="Control signal"/> * 100',
    )
    column("First acquisition", valueType="formula", formula='<Cell column="Acquired"[1]/>')
    column(
        "Previous delta",
        valueType="formula",
        formula='<Cell column="Acquired"/> - <Cell column="Acquired"[-1]/>',
    )
    column(
        "Next delta",
        valueType="formula",
        formula='<Cell column="Acquired"/> - <Cell column="Acquired"[+1]/>',
    )
    column("Hidden events", statistic="Count", analysisPath="Ungated", ishiddencolumn="1")
    column("Double hidden", valueType="formula", formula='<Cell column="Hidden events"/> * 2')
    scoped = ET.SubElement(editor, "Table", name="Control only")
    ET.SubElement(scoped, "Iteration", iterationType="SAMPLE", groupName="Control only")
    ET.SubElement(
        scoped,
        "TColumn",
        valueType="statistic",
        name="Count",
        rename="Acquired",
        statistic="Count",
        analysisPath="Ungated",
    )
    return root


def workspace_bytes():
    return ET.tostring(workspace_tree(), encoding="utf-8", xml_declaration=True)


if __name__ == "__main__":
    import json

    from import_fixture import fcs_dataset

    directory = Path("artifacts/wsp-table-fixture")
    directory.mkdir(parents=True, exist_ok=True)
    for name, values in zip(NAMES, VALUES, strict=True):
        (directory / name).write_bytes(fcs_dataset(values, ["X", "Y"]))
    (directory / "tables.wsp").write_bytes(workspace_bytes())
    (directory / "truth.json").write_text(json.dumps(TRUTH, indent=2) + "\n")
    print(str(directory.resolve()))
